# Generated by Django 2.0.2 on 2019-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['create'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='enlace'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creacion'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizacion'),
        ),
    ]
